version: "3"

services:

    php:
        build:
            context: .
            args:
                TIMEZONE: ${TIMEZONE}
#        volumes:
#            - ../.:/var/www/symfony/
        networks:
            - symfony

    nginx:
        build:
            context: docker/nginx
        volumes:
            - ../.:/var/www/symfony/
        ports:
            - "8004:80"
        networks:
            - symfony
        env_file:
            - docker/.env.nginx

networks:
    symfony:
