services:

    php:
        build:
            dockerfile: Dockerfile
        volumes:
            - project:/var/www/symfony/
        networks:
            - symfony

    nginx:
        build:
            context: docker/nginx
        volumes:
            - project:/var/www/symfony/
        networks:
            - symfony
        env_file:
            - docker/.env.nginx

volumes:
    project:

networks:
    symfony:
