version: "3"

services:

    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../.:/var/www/symfony/
        networks:
            - symfony

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../.:/var/www/symfony/
        ports:
            - "8002:80"
        networks:
            - symfony
        env_file:
            - .env.nginx

networks:
    symfony:
